changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - feat
        - docs
        - refactor
        - test
        - perf
    - title: Bug Fixes 🐛
      labels:
        - fix
    - title: Other Changes 📦
      labels:
        - "*"